kind: pipeline
name: build pipe

steps:
- name: build test
  image: rust:1.71
  commands:
  - apt-get update
  - apt-get install -y libpcap-dev
  - cargo build --verbose --all
trigger:
  branch:
  - main
  event:
  - push

---
kind: pipeline
name: test pipe

steps:
- name: test
  image: rust:1.71
  commands:
  - apt-get update
  - apt-get install -y libpcap-dev
  - cargo test --verbose --all
  
trigger:
  branch:
  - main
  event:
  - push
