kind: pipeline
name: default

steps:
- name: test
  image: rust:1.71
  commands:
  - apt-get update
  - apt-get install -y libpcap-dev
  - cargo build --verbose --all
  - cargo test --verbose --all
  
trigger:
  branch:
  - main
  event:
  - push
