kind: pipeline
name: build_pipe

steps:
- name: build
  image: rust:1.71
  commands:
  - apt-get update
  - apt-get install -y libpcap-dev
  - cargo build --verbose --all
  
trigger:
  branch:
  - main
  event:
  - push

---
kind: pipeline
name: test_pipe

steps:
- name: test
  image: rust:1.71
  commands:
  - apt-get update
  - apt-get install -y libpcap-dev
  - cargo test --verbose --all
  
trigger:
  branch:
  - main
  event:
  - push
