kind: pipeline
name: build_pipe
trigger:
  event:
  - push
  - pull_request

steps:
- name: build
  image: rust:1.71
  commands:
  - apt-get update
  - apt-get install -y libpcap-dev
  - cargo build --verbose --all

---
kind: pipeline
name: test_pipe
trigger:
  event:
  - push
  - pull_request

steps:
- name: test
  image: rust:1.71
  commands:
  - apt-get update
  - apt-get install -y libpcap-dev
  - cargo test --verbose --all

  

