[package]
name = "fluere-plugin-trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc-channel = "0.17.0"

[lib]
name = "fluere_plugin_trait"
