[package]
name = "fluere_plugin"
version = "0.1.0"
authors = ["Skuld Norniern <skuldnorniern@gmail.com>"]
edition = "2021"
description = "Plugin API for Fluere."
readme = "README.md"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc-channel = "0.17.0"
tokio = { version = "1.32", features = ["full","macros", "rt-multi-thread"] }
fluere-config = { path = "../fluere-config" }

[lib]
name = "fluere_plugin"
